pii_mapping:
  FIRSTNAME: PERSON
  LASTNAME: PERSON
  MIDDLENAME: PERSON
  PHONENUMBER: PHONE_NUMBER
  EMAIL: EMAIL_ADDRESS
  IPV4: IP_ADDRESS
  IPV6: IP_ADDRESS
  URL: URL
  IBAN: IBAN_CODE
  CREDITCARDNUMBER: CREDIT_CARD
  BITCOINADDRESS: CRYPTO
  DOB: DATE_TIME
  DATE: DATE_TIME
  TIME: DATE_TIME
  SSN: US_SSN
  STREET: ADDRESS
  CITY: ADDRESS
  STATE: ADDRESS
  ZIP: ADDRESS
  COUNTRY: ADDRESS

pii_types:
  recognized:
    - PERSON
    - PHONE_NUMBER
    - EMAIL_ADDRESS
    - IP_ADDRESS
    - URL
    - IBAN_CODE
    - CREDIT_CARD
    - CRYPTO
    - DATE_TIME
    - US_SSN
    - ADDRESS

  unrecognized:
    - UNKNOWN_TYPE_1
    - UNKNOWN_TYPE_2

dataset_filepath: "path/to/dataset.csv"